theme: jekyll-theme-cayman

title: msdn script center repro
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  clone from script center repo
baseurl: /msdn-scriptcenter-repo # the subpath of your site, e.g. /blog
sourcebaseurl: http://github.com/brwilkinson/msdn-scriptcenter-repo/tree/main
url: brwilkinson.github.io/msdn-scriptcenter-repo/
twitter_username: brwilkinson
github_username:  brwilkinson

user: 
  name: "brwilkinson"
  email: ""
  website: "linktr.ee/brwilkinson"
  twitter: twitter.com/brwilkinson
  avatar: "/assets/res/user.png"
  github: "brwilkinson"
